internal class Program {

	private static void Main(string[] args) {
		Console.WriteLine("=====================================================");
		PrintDisclaimer();

		var bee = new ParserWorkerBee();
		bee.RunParser();

		Console.WriteLine("=====================================================");
		Console.WriteLine("                       DONE");
		Thread.Sleep(500);

		PrintDisclaimer();
		Thread.Sleep(15 * 1000);
	}

	public static void PrintDisclaimer() {
		Console.WriteLine();
		Console.WriteLine();
		Console.ForegroundColor = ConsoleColor.Yellow;
		Console.WriteLine("================================================================================");
		Console.WriteLine("                                  DISCLAIMER                                    ");
		Console.WriteLine("================================================================================");
		Console.ResetColor();

		Console.WriteLine("1. AS-IS WARRANTY: THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY");
		Console.WriteLine("   KIND, EXPRESS OR IMPLIED. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT");
		Console.WriteLine("   HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN");
		Console.WriteLine("   ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN");
		Console.WriteLine("   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.");
		Console.WriteLine("2. NOT AN EXPERT: The developer is NOT a tax professional, CPA, or financial");
		Console.WriteLine("   advisor. This software is for informational purposes only.");
		Console.WriteLine("3. RESEARCH & DISCOVERY TOOL: This application is intended solely as a");
		Console.WriteLine("   research or discovery tool to assist with high-level income tabulation");
		Console.WriteLine("   and identifying potential wash sales. It is NOT a substitute for");
		Console.WriteLine("   professional advice or official tax documentation.");
		Console.WriteLine("4. CONSULT A PROFESSIONAL: If you have questions regarding your tax situation");
		Console.WriteLine("   or do not understand the output of this tool, you must consult a qualified");
		Console.WriteLine("   financial or tax expert.");
		Console.WriteLine("5. VERIFICATION REQUIRED: The user is solely responsible for performing their");
		Console.WriteLine("   own due diligence and verifying all data generated by this tool.");

		Console.ForegroundColor = ConsoleColor.Yellow;
		Console.WriteLine("================================================================================");
		Console.ResetColor();
		Console.WriteLine();
		Console.WriteLine();
	}
}